"""users table

Revision ID: e99d1e95ce3b
Revises: 3a26ec84d8fa
Create Date: 2018-04-11 20:21:43.254076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99d1e95ce3b'
down_revision = '3a26ec84d8fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_date'), 'user', ['date'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_date'), table_name='user')
    op.drop_column('user', 'date')
    # ### end Alembic commands ###
